#Example register configuration file (used by mkregs.py script)

[[latex_table1]]
#Registers belonging to latex table 1
REG1_NAME = {rw_type="W", nbits=1, rst_val=0, addr=-1, addr_w=0, autologic=true, description="REG1 description"} #Example write register
REG2_NAME = {rw_type="R", nbits=1, rst_val=0, addr=-1, addr_w=0, autologic=true, description="REG2 description"} #Example read register
REG3_NAME = {rw_type="W", nbits=8, rst_val=0, addr=-1, addr_w=0, autologic=true, description="REG3 description"} #Example 8-bit write register

[[latex_table2]]
#Registers belonging to latex table 2
REG4_NAME = {rw_type="W", nbits=1, rst_val=0, addr=-1, addr_w=0, autologic=true, description="REG4 description"} #Example write register
REG5_NAME = {rw_type="R", nbits=1, rst_val=0, addr=-1, addr_w=0, autologic=true, description="REG5 description"} #Example read register
